### ISSUE TITLE
May I ask where did you find the usage of SmartSSD?

### ISSUE THREAD

**Issue by PKUZHOU** [uyt8989/smartssd#1]
Thanks very much for providing these smartSSD examples. 
I am learning SmartSSD now, but also struggling to find the documents teaching about how to write SmartSSD programs.   May I ask how did you learn to write these examples?  From my knowledge, the Vitis Libraries contain some codes, did you learn from that? 

I am willing to hear from you.
Thank you!

**Comment by uyt8989** [comment]
I usually referenced [Github](https://github.com/Xilinx/Vitis_Accel_Examples). There are many example codes of it.
Also I used a document of smartSSD at Xilinx website. (To be honest, it was not very helped for coding).

I hope it helps you.
Thank you.

**Comment by PKUZHOU** [comment]
Thank you for your quick response!
Yes, I have also found that the SmartSSD document contains little information about how to write codes. 
However, I have learned much from your examples, it has clearly shown how the SmartSSD codes function. 
I will dive into this official github repo for more information, thank you again for your suggestion.
